### ISSUE TITLE
Change all instances of AddressBook inside the code

### ISSUE THREAD

**Issue by aaronseahyh** [CS2103-AY1819S1-W14-1/main#128]
**Describe the bug**
`AddressBook` instances are still in `ClinicIO`

**To Reproduce**
1. `Ctrl F` to find instances of `AddressBook`
2. Replace with `ClinicIO`

**Expected behavior**
Replace all instances of `AddressBook` to `ClinicIO`

**Comment by jjlee050** [comment]
Refer to #133
